version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run linter
          command: npm run lint
      # - run:
      #     name: Run tests
      #     command: npm run test
      # - run:
      #     name: Generate test coverage
      #     command: npm run test:coverage
      # - codecov/upload:
      #     file: coverage/lcov.info
      - run:
          name: Run build
          command: npm run build
      - run:
          name: Run bundlesize
          command: npm run bundlesize
      - persist_to_workspace:
          root: ~/project
          paths:
            - dist
  deploy:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Init npm
          command: npm init -y
      - run:
          name: Install Netlify CLI
          command: npm install --save-dev netlify-cli
      - run:
          name: Deploy to Netlify
          command: ./node_modules/.bin/netlify deploy --dir=build --prod

workflows:
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
