version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run linter
          command: npm run lint
      # - run:
      #     name: Run tests
      #     command: npm run test
      # - run:
      #     name: Generate test coverage
      #     command: npm run test:coverage
      # - codecov/upload:
      #     file: coverage/lcov.info
      - run:
          name: Run build
          command: npm run build
      - run:
          name: Run bundlesize
          command: npm run bundlesize
      - persist_to_workspace:
          root: ~/project
          paths:
            - build
            - package.json
            - README.md
  deploy:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Setup npm token
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN_RW}" >> build/npm/.npmrc
      - run:
          name: Publish to npm
          command: cp package.json build/npm && cp README.md build/npm && cd build/npm && npm publish

workflows:
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
