on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Install npm dependencies
        run: npm install
      - name: Create npm build
        run: npm run build
      - name: Release
        run: npm run release
