name: Release to npm

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Install npm dependencies
        run: npm install
      - name: Create build
        run: npm run build
      - name: Authenticate with the npm registry
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
      - name: Release
        run: npm run release
